# Close stale issues after a defined period of time.
#
name: Close Stale Issues

on:
  issues:
    types: [reopened]
  schedule:
  - cron: "30 4 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose stale issues.
      uses: actions/stale@v8
      with:
        days-before-close: 7
        days-before-stale: 21
        exempt-issue-labels: 'do-not-remove,in-progress'
        exempt-pr-labels: 'do-not-remove,in-progress'
        remove-stale-when-updated: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: 'stale'
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs. Thank you for your contributions.'
        stale-pr-label: 'stale'
        stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs. Thank you for your contributions.'
